DROP TABLE IF EXISTS jaegers;

\c Robots;

CREATE TABLE jaegers (
                         id         int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                         model_name VARCHAR(50),
                         mark       VARCHAR(10),
                         height     REAL,
                         weight     REAL,
                         status     VARCHAR(9),
                         origin     VARCHAR(50),
                         launch     DATE,
                         kaiju_kill int
);

\ir 'init_db.sql'
\ir 'queries.sql'