\c Robots;

DROP TABLE IF EXISTS jaegers;

CREATE TABLE jaegers (
    id         INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    model_name VARCHAR(50),
    mark       VARCHAR(10),
    height     REAL,
    weight     REAL,
    status     VARCHAR(9),
    origin     VARCHAR(50),
    launch     DATE,
    kaiju_kill INT
);

\ir 'init_db.sql'
\ir 'queries.sql'